### PR TITLE
Migrate CircleCI config from 1.0 to 2.0

### PR DESCRIPTION
**Pull request by lgsds**

### CODE REVIEW

**Review by sorensenjs — APPROVED** [review]

**Comment by lgsds** [comment]
This has become a bit of a rabbit hole unfortunately. Things I've done so far include:

* Fixing lint issues
* Trying to migrate circle.yml config from 1.0 to 2.0. There's lots of things in the previous config that I'm not sure we need (e.g. the caching), so I've stripped out most of it and kept things barebones
* [Mocking CSS modules](https://jestjs.io/docs/en/webpack#mocking-css-modules) for the `import 'react-perfect-scrollbar/dist/css/styles.css';` in `FilterSideBar.tsx`, which was causing test failures
* Updating outdated packages and fixing version mismatches in packages/frontend-web
* Updating outdated snapshots
* Excluding tests that are seeing failures exactly like [this](https://github.com/goldenyz/react-perfect-scrollbar/issues/72); seems like there's no fix for it. To exclude the tests, I added `storyNameRegex` to `Storyshots.test.js` to filter out tests with `DontTest` in the name

Unfortunately we're still seeing [failures](https://app.circleci.com/pipelines/github/conversationai/conversationai-moderator/9/workflows/8e3bfb54-a51d-4a8f-8129-4c904ea05fdd/jobs/9) in CircleCI when running `./bin/lint`. I think it's something related to storybook and webpack, but I'm not familiar enough with them or this repo to understand what's happening. It may be easier to just strip out all the snapshot testing at this point.

**Comment by RufusHamade** [comment]
Sorry, just noticed this review.  I'll see if I can fix the conflicts and test out the changes today.

**Review by RufusHamade — APPROVED** [review]
LGTM

**Comment by RufusHamade** [comment]
I can't do this last bit of a merge, as I can't push directly to master:-(  But should be all OK to land.  Just use the migrate-circleci version of packages/frontend-web/package-lock.json.

**Pull request merged**
